### PR TITLE
Seplilng msiatake

### PR DESCRIPTION
**Pull request by Revanth-Kausikan**
Corrected spelling mistake that persisted since the beginning of the universe.

### CODE REVIEW

**Comment by Revanth-Kausikan** [comment]
Do I have to type a comment?

**Comment by jagannathbhat1998** [comment]
Thanks for making the changes. I am deeply thankful for your service.

**Comment by jagannathbhat1998** [comment]
Thanks for making the changes. I am deeply thankful for your service.

**Comment by Revanth-Kausikan** [comment]
XD

Back to business, now pay me up.

**Comment by jagannathbhat1998** [comment]
I'll pay you respect.

You have my respect.

**Pull request merged**
